"""Compose snippet generator — the bounded slice of issue #7.

Given a stream id, emits the docker-compose service block and .env additions
the practitioner pastes into the host compose
(/opt/services/kanyo-admin/docker-compose.yml) to run a detector for that
stream. Generation only: no container is created, stopped, or monitored —
live orchestration (Docker SDK / compose regeneration / operator, issue #7's
options A–C) stays future work.

The emitted block mirrors the canonical template's per-stream pattern
(docker/docker-compose.yml): YAML-anchor inheritance from
x-kanyo-gpu-service, a KANYO_<ID>_ROOT env-var root for the volume mounts,
and an opt-in profile like the template's bigbear example so pasting the
block never changes what `docker compose up -d` starts by default.

# MIRROR — keep the volume/anchor pattern in sync with the bigbear-gpu
# service in docker/docker-compose.yml (pinned by
# tests/test_admin_compose_snippet.py, which parses the real template).
"""

DEFAULT_HOST_ROOT = "/opt/services"


def env_var_name(stream_id: str) -> str:
    """Env var carrying the stream's host root: KANYO_<ID>_ROOT.

    Hyphens become underscores (hyphens are valid in stream ids but not in
    env var names).
    """
    return f"KANYO_{stream_id.upper().replace('-', '_')}_ROOT"


def build_service_block(stream_id: str) -> str:
    """The compose service block to paste under `services:` in the host compose."""
    var = env_var_name(stream_id)
    return (
        f"  # {stream_id} — generated by the admin dashboard (paste under services:)\n"
        f"  # Start explicitly:  docker compose --profile {stream_id} up -d {stream_id}-gpu\n"
        f"  # Remove the profiles line to include it in the default `up -d` set.\n"
        f"  {stream_id}-gpu:\n"
        f"    <<: *kanyo-gpu-service\n"
        f"    container_name: kanyo-{stream_id}-gpu\n"
        f'    profiles: ["{stream_id}"]\n'
        f"    volumes:\n"
        f"      - ${{KANYO_CODE_ROOT}}/cookies.txt:/app/cookies.txt:rw\n"
        f"      - ${{{var}}}/config.yaml:/app/config.yaml:ro\n"
        f"      - ${{{var}}}/clips:/app/clips\n"
        f"      - ${{{var}}}/logs:/app/logs\n"
    )


def build_env_lines(stream_id: str, host_root: str = DEFAULT_HOST_ROOT) -> str:
    """The .env addition pointing the service block at the stream's host dir."""
    return f"{env_var_name(stream_id)}={host_root}/kanyo-{stream_id}\n"


def build_up_command(stream_id: str) -> str:
    """The explicit start command for the profiled service."""
    return f"docker compose --profile {stream_id} up -d {stream_id}-gpu"


def build_snippet(stream_id: str, host_root: str = DEFAULT_HOST_ROOT) -> str:
    """Full paste-ready text: .env addition + service block + start command."""
    return (
        f"# ── Add to /opt/services/kanyo-admin/.env "
        f"─────────────────────────────────\n"
        f"{build_env_lines(stream_id, host_root)}"
        f"\n"
        f"# ── Add under services: in /opt/services/kanyo-admin/docker-compose.yml ──\n"
        f"{build_service_block(stream_id)}"
        f"\n"
        f"# ── Then start it ────────────────────────────────────────────────────────\n"
        f"# {build_up_command(stream_id)}\n"
    )
