"""Stream creation and management."""

import yaml
import re
import subprocess
from pathlib import Path
from typing import Optional


# Template for new stream config
CONFIG_TEMPLATE = """# Kanyo Stream Configuration
# Generated by Admin GUI

stream_name: "{name}"
video_source: "{video_source}"

# Detection settings
detection_confidence: 0.5
frame_interval: 3
detect_any_animal: false

# State machine timing (seconds)
exit_timeout: 90
roosting_threshold: 1800

# Timezone offset from UTC
timezone: "{timezone}"

# Notifications
telegram_enabled: {telegram_enabled}
telegram_channel: "{telegram_channel}"
telegram_bot_token_env: "TELEGRAM_BOT_TOKEN"

# Clip generation
buffer_duration: 120
clip_before_event: 5
clip_after_event: 3

# Notification cooldowns (seconds)
arrival_cooldown: 300
departure_cooldown: 300

# Model path (using default from image)
model_path: "/app/models/yolo11x.pt"
"""

# Paths
SERVICES_BASE = Path("/opt/services")
ADMIN_COMPOSE = Path("/opt/services/kanyo-admin/docker-compose.yml")


def validate_stream_id(stream_id: str) -> tuple[bool, str]:
    """Validate stream ID format."""
    if not stream_id:
        return False, "Stream ID is required"
    if not re.match(r"^[a-z][a-z0-9_-]*$", stream_id):
        return False, "Stream ID must start with lowercase letter, contain only a-z, 0-9, _, -"
    if len(stream_id) > 32:
        return False, "Stream ID must be 32 characters or less"
    if stream_id in ["admin", "nvidia", "code", "new"]:
        return False, f"'{stream_id}' is a reserved name"
    return True, ""


def create_stream(
    stream_id: str,
    name: str,
    video_source: str,
    timezone: str = "+00:00",
    telegram_enabled: bool = False,
    telegram_channel: str = "",
) -> tuple[bool, str]:
    """
    Create a new stream with all necessary configuration.

    Returns:
        Tuple of (success, message)
    """
    # Validate
    valid, error = validate_stream_id(stream_id)
    if not valid:
        return False, error

    if not video_source.startswith("http"):
        return False, "Video source must be a valid URL"

    stream_dir = SERVICES_BASE / f"kanyo-{stream_id}"

    # Check if already exists
    if stream_dir.exists():
        return False, f"Stream directory already exists: {stream_dir}"

    try:
        # 1. Create directory structure
        stream_dir.mkdir(parents=True)
        (stream_dir / "clips").mkdir()
        (stream_dir / "logs").mkdir()

        # 2. Generate config.yaml
        config_content = CONFIG_TEMPLATE.format(
            name=name,
            video_source=video_source,
            timezone=timezone,
            telegram_enabled=str(telegram_enabled).lower(),
            telegram_channel=telegram_channel or "",
        )
        (stream_dir / "config.yaml").write_text(config_content)

        # 3. Add to detection docker-compose.yml
        success, msg = _add_to_detection_compose(stream_id)
        if not success:
            _cleanup(stream_dir)
            return False, f"Failed to update detection compose: {msg}"

        # 4. Add volume mount to admin docker-compose.yml
        success, msg = _add_admin_volume(stream_id, stream_dir)
        if not success:
            _cleanup(stream_dir)
            return False, f"Failed to update admin compose: {msg}"

        # 5. Start the new detection container
        success, msg = _start_detection_container(stream_id)
        if not success:
            # Don't cleanup - compose files are updated, just container didn't start
            return False, f"Stream created but container failed to start: {msg}"

        return True, f"Stream '{name}' created and container started!"

    except Exception as e:
        _cleanup(stream_dir)
        return False, f"Error creating stream: {str(e)}"


def _cleanup(stream_dir: Path):
    """Remove stream directory on failure."""
    if stream_dir.exists():
        import shutil

        shutil.rmtree(stream_dir)


def _add_to_detection_compose(stream_id: str) -> tuple[bool, str]:
    """Add new service to detection docker-compose.yml."""
    compose_path = ADMIN_COMPOSE  # Both services are in the admin compose file

    if not compose_path.exists():
        return False, f"Compose file not found: {compose_path}"

    try:
        with open(compose_path) as f:
            compose = yaml.safe_load(f)

        container_name = f"kanyo-{stream_id}-gpu"

        # Check if already exists
        if f"{stream_id}-gpu" in compose.get("services", {}):
            return True, "Service already exists"

        # Find an existing kanyo service to copy structure from
        template_service = None
        for svc_name, svc_config in compose.get("services", {}).items():
            if svc_name.startswith("harvard-") or svc_name.startswith("nsw-"):
                template_service = svc_config.copy()
                break

        if not template_service:
            return False, "No template service found to copy from"

        # Create new service based on template
        new_service = template_service.copy()
        new_service["container_name"] = container_name

        # Update volumes
        new_volumes = []
        for vol in new_service.get("volumes", []):
            if "/config.yaml" in vol:
                new_volumes.append(
                    f"${{KANYO_{stream_id.upper()}_ROOT:-./data/{stream_id}}}/config.yaml:/app/config.yaml:ro"
                )
            elif "/clips" in vol:
                new_volumes.append(
                    f"${{KANYO_{stream_id.upper()}_ROOT:-./data/{stream_id}}}/clips:/app/clips"
                )
            elif "/logs" in vol:
                new_volumes.append(
                    f"${{KANYO_{stream_id.upper()}_ROOT:-./data/{stream_id}}}/logs:/app/logs"
                )
            else:
                new_volumes.append(vol)

        new_service["volumes"] = new_volumes

        # Add the new service
        compose["services"][f"{stream_id}-gpu"] = new_service

        with open(compose_path, "w") as f:
            yaml.dump(compose, f, default_flow_style=False, sort_keys=False)

        return True, "Added to compose"

    except Exception as e:
        return False, str(e)


def _add_admin_volume(stream_id: str, stream_dir: Path) -> tuple[bool, str]:
    """Add volume mount to admin docker-compose.yml."""
    if not ADMIN_COMPOSE.exists():
        return False, f"Admin compose file not found: {ADMIN_COMPOSE}"

    try:
        with open(ADMIN_COMPOSE) as f:
            compose = yaml.safe_load(f)

        # Find admin/dashboard service
        service_name = None
        for name in ["dashboard", "admin"]:
            if name in compose.get("services", {}):
                service_name = name
                break

        if not service_name:
            return False, "No dashboard or admin service found"

        volumes = compose["services"][service_name].get("volumes", [])
        new_volume = f"${{KANYO_{stream_id.upper()}_ROOT:-./data/{stream_id}}}:/data/{stream_id}"

        # Check if already exists
        if any(f"/data/{stream_id}" in v for v in volumes):
            return True, "Volume already exists"

        volumes.append(new_volume)
        compose["services"][service_name]["volumes"] = volumes

        with open(ADMIN_COMPOSE, "w") as f:
            yaml.dump(compose, f, default_flow_style=False, sort_keys=False)

        return True, "Added admin volume"

    except Exception as e:
        return False, str(e)


def _start_detection_container(stream_id: str) -> tuple[bool, str]:
    """Start the new detection container."""
    try:
        service_name = f"{stream_id}-gpu"
        result = subprocess.run(
            ["docker-compose", "-f", str(ADMIN_COMPOSE), "up", "-d", service_name],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=ADMIN_COMPOSE.parent,
        )

        if result.returncode == 0:
            return True, "Container started"
        else:
            return False, result.stderr or result.stdout

    except subprocess.TimeoutExpired:
        return False, "Timeout starting container"
    except Exception as e:
        return False, str(e)


def restart_admin_container() -> tuple[bool, str]:
    """Restart the admin container itself."""
    try:
        # Get our own container name
        result = subprocess.run(
            ["hostname"],
            capture_output=True,
            text=True,
        )
        container_id = result.stdout.strip()

        # Schedule restart (docker will restart us)
        # Use nohup to ensure the restart command continues after we die
        subprocess.Popen(
            ["sh", "-c", f"sleep 2 && docker restart {container_id}"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )

        return True, "Admin restart scheduled"

    except Exception as e:
        return False, str(e)


def get_available_streams() -> list[str]:
    """Get list of stream IDs that could be added (have dirs but not in compose)."""
    # This could be useful for detecting orphaned streams
    existing = []
    if SERVICES_BASE.exists():
        for d in SERVICES_BASE.iterdir():
            if (
                d.is_dir()
                and d.name.startswith("kanyo-")
                and d.name not in ["kanyo-admin", "kanyo-nvidia", "kanyo-code"]
            ):
                stream_id = d.name.replace("kanyo-", "")
                existing.append(stream_id)
    return existing
