"""Stream creation and management."""

import yaml
import re
from pathlib import Path
from typing import Optional


# Template for new stream config
CONFIG_TEMPLATE = """# Kanyo Stream Configuration
# Generated by Admin GUI

stream_name: "{name}"
video_source: "{video_source}"

# Detection settings
detection_confidence: 0.5
frame_interval: 3
detect_any_animal: false

# State machine timing (seconds)
exit_timeout: 90
roosting_threshold: 1800

# Timezone offset from UTC
timezone: "{timezone}"

# Notifications
telegram_enabled: {telegram_enabled}
telegram_channel: "{telegram_channel}"
telegram_bot_token_env: "TELEGRAM_BOT_TOKEN"

# Clip generation
buffer_duration: 120
clip_before_event: 5
clip_after_event: 3

# Notification cooldowns (seconds)
arrival_cooldown: 300
departure_cooldown: 300
"""


def validate_stream_id(stream_id: str) -> tuple[bool, str]:
    """Validate stream ID format."""
    if not stream_id:
        return False, "Stream ID is required"
    if not re.match(r'^[a-z][a-z0-9_-]*$', stream_id):
        return False, "Stream ID must start with lowercase letter, contain only a-z, 0-9, _, -"
    if len(stream_id) > 32:
        return False, "Stream ID must be 32 characters or less"
    return True, ""


def create_stream(
    stream_id: str,
    name: str,
    video_source: str,
    timezone: str = "+00:00",
    telegram_enabled: bool = False,
    telegram_channel: str = "",
    base_path: Path = Path("/data"),
    compose_path: Path = Path("/opt/services/kanyo-nvidia/docker-compose.yml"),
    admin_compose_path: Path = Path("/opt/services/kanyo-admin/docker-compose.yml"),
) -> tuple[bool, str]:
    """
    Create a new stream with all necessary configuration.

    Returns:
        Tuple of (success, message)
    """
    # Validate
    valid, error = validate_stream_id(stream_id)
    if not valid:
        return False, error

    stream_dir = base_path / stream_id

    # Check if already exists
    if stream_dir.exists():
        return False, f"Stream directory already exists: {stream_dir}"

    try:
        # 1. Create directory structure
        stream_dir.mkdir(parents=True)
        (stream_dir / "clips").mkdir()
        (stream_dir / "logs").mkdir()

        # 2. Generate config.yaml
        config_content = CONFIG_TEMPLATE.format(
            name=name,
            video_source=video_source,
            timezone=timezone,
            telegram_enabled=str(telegram_enabled).lower(),
            telegram_channel=telegram_channel,
        )
        (stream_dir / "config.yaml").write_text(config_content)

        # 3. Add to detection docker-compose.yml (if exists)
        if compose_path.exists():
            if not _add_to_compose(stream_id, compose_path):
                return False, "Failed to update docker-compose.yml"

        # 4. Add volume mount to admin docker-compose.yml (if exists)
        if admin_compose_path.exists():
            if not _add_admin_volume(stream_id, stream_dir, admin_compose_path):
                return False, "Failed to update admin docker-compose.yml"

        return True, f"Stream '{stream_id}' created successfully. Run 'docker compose up -d' to start."

    except Exception as e:
        # Cleanup on failure
        if stream_dir.exists():
            import shutil
            shutil.rmtree(stream_dir)
        return False, f"Error creating stream: {str(e)}"


def _add_to_compose(stream_id: str, compose_path: Path) -> bool:
    """Add new service to docker-compose.yml."""
    if not compose_path.exists():
        return False

    with open(compose_path) as f:
        compose = yaml.safe_load(f)

    service_name = f"{stream_id}-gpu"

    # Check if already exists
    if service_name in compose.get("services", {}):
        return True  # Already exists

    # Add new service (copy structure from existing)
    compose["services"][service_name] = {
        "image": "kanyo-detection:latest",
        "container_name": f"kanyo-{service_name}",
        "runtime": "nvidia",
        "environment": [
            "NVIDIA_VISIBLE_DEVICES=all",
        ],
        "volumes": [
            f"/data/{stream_id}:/data",
        ],
        "env_file": [".env"],
        "restart": "unless-stopped",
        "logging": {
            "driver": "json-file",
            "options": {
                "max-size": "10m",
                "max-file": "3",
            },
        },
    }

    with open(compose_path, "w") as f:
        yaml.dump(compose, f, default_flow_style=False, sort_keys=False)

    return True


def _add_admin_volume(stream_id: str, stream_dir: Path, admin_compose_path: Path) -> bool:
    """Add volume mount to admin docker-compose.yml."""
    if not admin_compose_path.exists():
        return False

    with open(admin_compose_path) as f:
        compose = yaml.safe_load(f)

    # Find admin/dashboard service
    for service_name in ["dashboard", "admin"]:
        if service_name in compose.get("services", {}):
            volumes = compose["services"][service_name].get("volumes", [])
            new_volume = f"{stream_dir}:/data/{stream_id}:ro"

            if new_volume not in volumes:
                volumes.append(new_volume)
                compose["services"][service_name]["volumes"] = volumes
            break

    with open(admin_compose_path, "w") as f:
        yaml.dump(compose, f, default_flow_style=False, sort_keys=False)

    return True
